### ISSUE TITLE
load the unit test params with default values

### ISSUE THREAD

**Issue by logicminds** [logicminds/puppet-retrospec#5]
once #3 is finished we should be able to supply the same default values to the params list.  This will require template access to the variable store.

**Comment by petems** [comment]
Just discovered this gem today, the params thing is the only negative I can find so far :dancer:

**Comment by logicminds** [comment]
I haven't really told anybody yet.  The next version is almost ready too.  Was waiting to solve some issues before making an announcement.

**Comment by logicminds** [comment]
@petems now available in 0.6.0
